#!/bin/zsh

zmodload zsh/datetime

integer offset=0

# parse those parameters into an associate array
typeset -A pars
# alternating key value pairs will do the right thing here
pars=( "$@" )

# set some default parameters, if they are not there
[[ -z $pars[-h] ]] && pars[-h]=20
[[ -z $pars[-p] ]] && pars[-p]=3
[[ -z $pars[-y] ]] && pars[-y]=0

# this is not threadsafe, but w/e
[[ -e /tmp/dzenlines ]] && l=( ${(f)"$(</tmp/dzenlines)"} )
[[ -n $l ]] && (( $l[1] > $EPOCHSECONDS )) && offset=$[ $l[2] +4 ]
echo "$(($EPOCHSECONDS+$pars[-p]))\n$(($offset+$pars[-h]))" > /tmp/dzenlines

# adjust y parameter
pars[-y]=$[ ${pars[-y]} + $offset ]

dzen2 ${(kv)pars}
