#!/bin/zsh

mpdst=( ${(f)"$(mpc -h ${1:-localhost} status -f '%artist% - %album% - %title%')"} )
setopt rematchpcre
[[ $mpdst[1] =~ '(.+) - (.+) - (.+)' ]] || return 1
ARTIST=$match[1]
ALBUM=$match[2]
SONG=$match[3]

#\d+/\d+ \s* (\d+:\d+)/(\d+:\d+) (\d+%)
[[ $mpdst[2] =~ '\[(\w+)\] #(\d+)/(\d+)\s+(\d+:\d+)/(\d+:\d+)\s+\((\d+)%\)' ]] || return 1
MPDSTATE=$match[1]
PL_NOW=$match[2]
PL_TOTAL=$match[3]
TIME_NOW=$match[4]
TIME_TOTAL=$match[5]
PERCENT=$match[6]
